//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteveTDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskId { get; set; }
        public long ListId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long Priority { get; set; }
        public long Complete { get; set; }
        public long Weight { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string DueDate { get; set; }
        public long Position { get; set; }
    }
}
